# Azure Devops pipeline to deploy ApplicationInsights functions.
# This cannot be done using Bicep because of a bug in the Bicep templates.

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - appInsights
    - appInsights-pipeline.yml 

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  name: terraformInit
  displayName: Initialize Terraform
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'appInsights'
    backendServiceArm: 'My Azure Resource manager for Prod subscription'
    backendAzureRmResourceGroupName: 'pma5-poc'
    backendAzureRmStorageAccountName: 'pma5pocstorage'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV4@4
  name: terraformPlan
  displayName: Create Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'appInsights'
    commandOptions: '-out main.tfplan'
    environmentServiceNameAzureRM: 'My Azure Resource manager for Prod subscription'

# Only runs if the 'terraformPlan' task has detected changes the in state. 
- task: TerraformTaskV4@4
  displayName: Apply Terraform Plan
  condition: eq(variables['terraformPlan.changesPresent'], 'true')
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'appInsights'
    commandOptions: 'main.tfplan'
    environmentServiceNameAzureRM: 'My Azure Resource manager for Prod subscription'

