
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - infra
    - infra-pipeline.yml

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'Triple Beta ARM Service Connection'
  resourceGroupName: 'pma5-poc'
  location: 'westeurope'
  templateFile: './infra/main.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'pma5poc-infra'