#
# Azure Devops pipeline to deplot Azure Automation infrastructure.
# Uses bicep. Original code comes from: https://github.com/jordanbean-msft/automation-ado
# Modular setup. Easy to make it fit for higher environments.
#
name: Deploy Automation

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - automation/infra
    exclude:
      - /**/*.md
  

variables:
  - name: environmentName
    value: 'dev'

stages:
  - stage: Deploy_to_Dev 
    jobs:
    - deployment: Dev
      pool:
        vmImage: windows-latest
      environment: $(environmentName)
      strategy:
        runOnce:
          deploy:
            steps:
            - template: deploy-automation-infra.yml
  
  # - stage: Deploy_to_Stg
  #   jobs:
  #   - deployment: Stg
  #     pool:
  #       vmImage: windows-latest
  #     environment: ${{ variables.stgEnvironmentName }}
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #           - template: deploy-infrastructure.yml
  #             parameters:
  #               azureServiceConnection: ${{ variables.serviceConnectionName }}
  #               resourceGroupName: ${{ variables.stgResourceGroupName }}
  #               environmentName: ${{ variables.stgEnvironmentName }}
  #               pathToInfrastructureDirectory: ${{ variables.pathToInfrastructureDirectory }}
  #               adoAccountName: ${{ variables.adoAccountName }}
  #               adoRepositoryName: ${{ variables.adoRepositoryName }}
  #               adoPat: $(AdoPat)
  #               pathToAutomationDirectory: ${{ variables.pathToAutomationDirectory }}
  # - stage: Deploy_to_Prd 
  #   jobs:
  #   - deployment: Prd
  #     pool:
  #       vmImage: windows-latest
  #     environment: ${{ variables.prdEnvironmentName }}
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #           - template: deploy-infrastructure.yml
  #             parameters:
  #               azureServiceConnection: ${{ variables.serviceConnectionName }}
  #               resourceGroupName: ${{ variables.prdResourceGroupName }}
  #               environmentName: ${{ variables.prdEnvironmentName }}
  #               pathToInfrastructureDirectory: ${{ variables.pathToInfrastructureDirectory }}
  #               adoAccountName: ${{ variables.adoAccountName }}
  #               adoRepositoryName: ${{ variables.adoRepositoryName }}
  #               adoPat: $(AdoPat)
  #               pathToAutomationDirectory: ${{ variables.pathToAutomationDirectory }}
