#
# Azure Devops pipeline to deplot Azure Automation infrastructure.
# Uses bicep. Original code comes from: https://github.com/jordanbean-msft/automation-ado
# Modular setup. Easy to make it fit for higher environments.
#
name: Deploy Automation

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - automation/infra
  
variables:
  - group: otelpoc
  - name: environmentName
    value: 'dev'


stages:
  - stage: Deploy_to_Dev 
    jobs:
    - deployment: Dev
      pool:
        vmImage: windows-latest
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                persistCredentials: true
              - template: print-env.yml
              - task: AzureCLI@2
                displayName: Compile Bicep to ARM
                inputs:
                  azureSubscription: $(azureServiceConnection)
                  workingDirectory: '$(System.DefaultWorkingDirectory)/automation/infra'
                  scriptType: ps
                  scriptLocation: inlineScript
                  inlineScript:  |
                    az bicep build -f main.bicep
              - task: AzureResourceGroupDeployment@2
                displayName: Deploy Azure Automation account
                inputs:
                  azureSubscription: $(azureServiceConnection)
                  resourceGroupName: $(resourceGroupName)
                  csmFile: $(System.DefaultWorkingDirectory)/automation/infra/main.json
                  csmParametersFile: $(System.DefaultWorkingDirectory)/automation/infra/env/$(environmentName).bicepparameters.json
              - task: AzurePowerShell@5
                displayName: Setup Source Control link between Automation Account and Azure DevOps Git repo
                inputs:
                  azureSubscription: $(azureServiceConnection)
                  ScriptType: FilePath
                  azurePowerShellVersion: latestVersion
                  ScriptPath: $(System.DefaultWorkingDirectory)/automation/infra/setup-source-control-link.ps1
                  ScriptArguments: 
                    -ResourceGroupName $(resourceGroupName)
                    -adoAccountName $(adoAccountName)
                    -RepositoryName $(adoRepositoryName)
                    -PathToRunbooks 'automation/runbooks'
                    -AdoPat $(AdoPat)
  