name: Deploy Runbooks and alerts

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - runbooks
    exclude:
      - /**/*.md

variables:
  - group: otelpoc
  - name: templateFile
    value: './alerts.bicep'

stages:
- stage: DeployAutomationInfra
  displayName: Deploy Azure Automation Runbooks
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest
    steps:       
      - checkout: self
        persistCredentials: true

      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTaskV4@4
        name: terraformInit
        displayName: Initialize Terraform
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'runbooks'
          backendServiceArm: $(azureServiceConnection)
          backendAzureRmResourceGroupName: $(resourceGroupName)
          backendAzureRmStorageAccountName: '$(resourceGroupName)storage'
          backendAzureRmContainerName: 'tfstate-runbook'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTaskV4@4
        name: terraformPlan
        displayName: Create Terraform Plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: 'runbooks'
          commandOptions: '-out main.tfplan'
          environmentServiceNameAzureRM: $(azureServiceConnection)

      # Only runs if the 'terraformPlan' task has detected changes the in state. 
      - task: TerraformTaskV4@4
        displayName: Apply Terraform Plan
        condition: eq(variables['terraformPlan.changesPresent'], 'true')
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: 'runbooks'
          commandOptions: 'main.tfplan'
          environmentServiceNameAzureRM: $(azureServiceConnection)
       

      # - task: AzurePowerShell@5
      #   displayName: Deploy Runbooks to Azure Automation
      #   inputs:
      #     azureSubscription: $(azureServiceConnection)
      #     scriptType: FilePath
      #     scriptPath: '$(System.DefaultWorkingDirectory)/automation/runbooks/deploy-runbooks.ps1'
      #     scriptArguments:
      #       -ResourceGroupName $(resourceGroupName)
      #     azurePowerShellVersion: latestVersion

      # - task: AzureResourceManagerTemplateDeployment@3
      #   displayName: Deploy Azure AlertRuleGroup to start a Runbook
      #   inputs:
      #     deploymentScope: 'Resource Group'
      #     azureResourceManagerConnection: '$(azureServiceConnection)'
      #     action: 'Create Or Update Resource Group'
      #     resourceGroupName: '$(resourceGroupName)'
      #     location: '$(location)'
      #     templateLocation: 'Linked artifact'
      #     csmFile: '$(templateFile)'
      #     deploymentMode: 'Incremental'
      #     deploymentName: '$(resourceGroupName)-alerts'