# Azure Devops pipeline to deploy ApplicationInsights functions.
# This cannot be done using Bicep because of a bug in the Bicep templates.

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - appInsights

pool:
  vmImage: ubuntu-latest

variables:
  # Azure Resource Manager connection created during pipeline creation
  - name: azureServiceConnection
    value: $(azureServiceConnection)

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  name: terraformInit
  displayName: Initialize Terraform
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'appInsights'
    backendServiceArm: azureServiceConnection
    backendAzureRmResourceGroupName: 'otelpoc'
    backendAzureRmStorageAccountName: 'otelpocstorage'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  name: terraformPlan
  displayName: Create Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'appInsights'
    commandOptions: '-out main.tfplan'
    environmentServiceNameAzureRM: azureServiceConnection

# Only runs if the 'terraformPlan' task has detected changes the in state. 
- task: TerraformTaskV4@4
  displayName: Apply Terraform Plan
  condition: eq(variables['terraformPlan.changesPresent'], 'true')
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'appInsights'
    commandOptions: 'main.tfplan'
    environmentServiceNameAzureRM: azureServiceConnection

