trigger:
  branches:
    include:
    - master

name: Deploy Bicep files

variables:
  # Azure Resource Manager connection created during pipeline creation
  - name: azureServiceConnection
    value: $(azureServiceConnection)

  - name: vmImageName
    value: 'ubuntu-latest'

  - name: resourceGroupName
    value: 'otelpoc'

  - name: location
    value: 'westeurope'

  - name: templateFile
    value: './infra/main.bicep'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'otelpoc-infra'
