parameters:
  # Azure Resource Manager connection created during pipeline creation
  - name: azureServiceConnection

trigger:
  branches:
    include:
    - master

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  resourceGroupName: 'otelpoc'
  location: 'westeurope'
  templateFile: './infra/main.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'otelpoc-infra'
