trigger:
  branches:
    include:
    - master
  paths:
    include:
      - azureFunctions/infra

name: Deploy Bicep files

variables:
  - group: otelpoc

  - name: templateFile
    value: 'azureFunctions/infra/main.bicep'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'otelpoc-infra'
