name: Deploy Runbooks and alerts

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - automation/runbooks
    exclude:
      - /**/*.md

variables:
  - group: otelpoc
  - name: templateFile
    value: 'automation/runbooks/alerts.bicep'

stages:
- stage: DeployAutomationInfra
  displayName: Deploy automation infra
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest
    steps:       
      - checkout: self
        persistCredentials: true
      - task: AzurePowerShell@5
        displayName: Deploy Python packages in the Automation account
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: FilePath
          scriptPath: '$(System.DefaultWorkingDirectory)/automation/runbooks/deploy-runbook-packages.ps1'
          scriptArguments:
            -ResourceGroupName $(resourceGroupName)
          azurePowerShellVersion: latestVersion
      - task: AzurePowerShell@5
        displayName: Deploy Runbooks to Azure Automation
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: FilePath
          scriptPath: '$(System.DefaultWorkingDirectory)/automation/runbooks/deploy-runbooks.ps1'
          scriptArguments:
            -ResourceGroupName $(resourceGroupName)
          azurePowerShellVersion: latestVersion
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Deploy Azure AlertRuleGroup to start a Runbook
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: '$(azureServiceConnection)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(resourceGroupName)'
          location: '$(location)'
          templateLocation: 'Linked artifact'
          csmFile: '$(templateFile)'
          deploymentMode: 'Incremental'
          deploymentName: '$(resourceGroupName)-alerts'